[project]
name = "tyler-course"
version = "0.1.0"
description = "Tyler course development environment"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jupyterlab>=4.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
